HSC-260: Add GA CI pipelines
mekomsolutions/ozone-haiti pull request #1
Opened 2024-07-17 03:37 UTC by enyachoke

2024-07-17 07:26 UTC, rbuisson requested changes

2024-07-17 07:26 UTC, rbuisson commented on .github/workflows/check-deps.yml
> +    - cron: '30 */12 * * *'
Since this is a public repo (we're not limited with GA minutes), you can set it to run hourly.

2024-07-17 07:26 UTC, rbuisson commented on pom.xml
> +      <id>sonatype-nexus-snapshots</id>
Do we need that one?

2024-07-17 07:29 UTC, rbuisson reviewed
In the PR for HSC, you have gitignored the effective-pom.xml. Is this needed here too?

2024-07-18 05:36 UTC, enyachoke commented
> In the PR for HSC, you have gitignored the effective-pom.xml. Is this needed here too?

The file was not created here but I have ignored it just in case

2024-07-18 06:32 UTC, merged